### ISSUE TITLE
Revert map to previous style

### ISSUE THREAD

**Issue by ClockworkMobius** [noelmurillo15/Project-Marmot#17]
I actually really liked the Metroid style map - it gave the information needed without too much distraction.  You did a great job on it.

**Comment by noelmurillo15** [comment]
Thank you, reverting the map style might take me some time, was easy to implement before because I was using a 2D tilemap and I created the mini-map by just scanning the individual tiles and mapping them to a particular color. I am currently using 3D terrain so i'll have to do a little research to see if i can get the same effect. The mini-map currently works via render texture with a 2nd camera that is only looking at certain layers.

**Comment by noelmurillo15** [comment]
Updated minimap to be similar-ish to what we had before and made it bigger with a background to cover 75% of the screen
