### ISSUE TITLE
Allow for viewing guidelines in game

### ISSUE THREAD

**Issue by ClockworkMobius** [noelmurillo15/Project-Marmot#31]
Preferably, this would be with a system that allows PDFs to be viewed in game.  In case that isn't feasible, I've emailed PNGs of two of the guidelines (the third case that we have - the one I originally sent - should probably be removed until I've formatted it properly).

**Comment by noelmurillo15** [comment]
Definitly feasible since there is a Unity Asset that does it -- https://assetstore.unity.com/packages/tools/gui/pdf-renderer-32815#description (although it costs $97). I could write my own but I think it would take a while to do whereas displaying the pdf as images would be done in an hour. If we have the time I can give it a shot, I would just have to learn the pdf api and translate the bytes into a Texture2D format.

**Comment by ClockworkMobius** [comment]
Let's go ahead and do this! Seems like a good idea.
